### ISSUE TITLE
no active host node

### ISSUE THREAD

**Issue by dparkerfmts** [briandunnington/roku-promise#2]
I'm trying to use roku-promise with a Task node but I'm getting the following error:
```
BRIGHTSCRIPT: ERROR: roSGNode.ObserveField: no active host node: pkg:/source/promise.brs(32)
```
 I'm using the code as follows:
```
createTaskPromise("fmTimer", {
     timeout: 5000
 }, "fire").then(sub(task)
     print "task " task
 end sub)
```

and the `fmTimer` Task component is as follows:
```
<?xml version="1.0" encoding="utf-8" ?>
<component name="fmTimer" extends="task">
    <interface>
        <field id="timeout" type="int"/>
        <field id="fire" type="boolean" value="false"/>
    </interface>

    <script type="text/brightscript">
        <![CDATA[
        sub init()
            print "Timer Node init"
            m.top.functionname="timer"
        end sub

        sub timer()
          clock = CreateObject("roTimespan")
          clock.Mark()

          while true
            ticks = clock.TotalMilliseconds()

            if (ticks > m.top.timeout)
              m.top.fire = true
              exit while
            end if
          end while
        end sub
        ]]>
    </script>

    <children>
    </children>
</component>
```

I can only assume my task node is not setup correctly?

**Comment by briandunnington** [comment]
@dparkerfmts Where are you calling `createTaskPromise` from? (From another Task, or from your UI thread?) Is the fmTimer xml file in the `components` folder? If you use `CreateObject` to create the task manually and try to observe the field, does it work? (that is all this library is doing for you, so I suspect that will not work either). You could try changing the case of the `extends=task` to `extends=Task` but I dont think that is it.

**Comment by briandunnington** [comment]
@dparkerfmts Did you get this sorted out? I haven't heard back so I am gonna close this. If you are still having issues, try the suggestions above and feel free to comment back on this issue.
